# Generated by Django 4.2.4 on 2023-09-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0013_product_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sizes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafts_by_micks.product_sizes'),
        ),
    ]
