# Generated by Django 4.2.4 on 2023-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0019_alter_product_sizes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sizes',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
