# Generated by Django 4.2.4 on 2023-09-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0021_label_custom_colour_alter_label_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='colour',
        ),
    ]
