# Generated by Django 4.2.4 on 2023-09-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0022_remove_label_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='discount',
        ),
    ]
