# Generated by Django 4.2.4 on 2023-09-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0024_remove_product_quantity_product_sizes_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
