# Generated by Django 4.2.4 on 2023-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0027_alter_category_title_alter_label_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, upload_to='products_images/'),
        ),
    ]
