# Generated by Django 4.2.4 on 2023-09-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0031_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='image_title',
        ),
    ]
