# Generated by Django 4.2.4 on 2023-09-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0034_order_item_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='customer',
        ),
    ]
