# Generated by Django 4.2.4 on 2023-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0039_alter_order_delivered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_value',
            field=models.FloatField(default=0.0),
        ),
    ]
