# Generated by Django 4.2.4 on 2023-09-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('discount', models.BooleanField()),
                ('discount_percentage', models.IntegerField(null=True)),
                ('creation_date', models.DateField()),
                ('removal_days', models.IntegerField(null=True)),
                ('colour', models.CharField(choices=[('Red', 'red'), ('Blue', 'blue'), ('Black', 'black'), ('Green', 'lime'), ('Yellow', 'yellow'), ('Gold', 'gold'), ('Aqua', 'aqua'), ('Purple', 'purple'), ('Salmon', 'salmon'), ('Clear', 'clear')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=100, null=True)),
                ('review_value', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crafts_by_micks.category')),
                ('labels', models.ManyToManyField(to='crafts_by_micks.label')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafts_by_micks.product')),
            ],
        ),
    ]
