# Generated by Django 4.2.4 on 2023-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='Product_Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('none', 'n'), ('extra-small', 'xs'), ('small', 'sm'), ('medium', 'm'), ('large', 'lg'), ('extra-large', 'xl'), ('XXL', 'xxl')], max_length=15)),
                ('price', models.FloatField()),
                ('product_id', models.ManyToManyField(to='crafts_by_micks.product')),
            ],
        ),
    ]
