# Generated by Django 4.2.4 on 2023-09-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0003_alter_product_sizes_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_sizes',
            name='product_id',
        ),
    ]
