# Generated by Django 4.2.4 on 2023-09-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0004_remove_product_sizes_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sizes',
            field=models.ManyToManyField(to='crafts_by_micks.product_sizes'),
        ),
    ]
