# Generated by Django 4.2.4 on 2023-09-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0007_product_sizes_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_sizes',
            name='product',
        ),
    ]
