# Generated by Django 4.2.4 on 2023-09-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0020_alter_product_sizes_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='custom_colour',
            field=models.CharField(default='#89CFF0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='colour',
            field=models.CharField(choices=[('Red', 'red'), ('Blue', 'blue'), ('Black', 'black'), ('Green', 'lime'), ('Yellow', 'yellow'), ('Gold', 'gold'), ('Aqua', 'aqua'), ('Purple', 'purple'), ('Salmon', 'salmon'), ('Clear', 'clear')], default='blue', max_length=15, null=True),
        ),
    ]
