# Generated by Django 4.2.4 on 2023-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0023_remove_label_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product_sizes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_sizes',
            name='size',
            field=models.CharField(choices=[('n', 'none'), ('xs', 'extra-small'), ('sm', 'small'), ('m', 'medium'), ('lg', 'large'), ('xl-large', 'extra-large'), ('xxl', 'XXL')], max_length=15),
        ),
    ]
