# Generated by Django 4.2.4 on 2023-09-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0025_remove_product_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_sizes',
            name='quantity',
        ),
    ]
