# Generated by Django 4.2.4 on 2023-09-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0028_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
