# Generated by Django 4.2.4 on 2023-09-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0030_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=30)),
                ('image', models.ImageField(default=None, upload_to='products_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafts_by_micks.product')),
            ],
        ),
    ]
