# Generated by Django 4.2.4 on 2023-09-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_by_micks', '0036_order_order_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_received_date',
            field=models.DateTimeField(default=None),
        ),
    ]
